### ISSUE TITLE
Deployment of NAV 2017 failed

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/nav-arm-templates#116]
I tried to deploy NAV2017.

Parameters:
```
"parameters": {
      "vmName": {
        "type": "String",
        "value": "***"
      },
      "timezoneId": {
        "type": "String",
        "value": "GMT Standard Time"
      },
      "acceptEula": {
        "type": "String",
        "value": "Yes"
      },
      "remoteDesktopAccess": {
        "type": "String",
        "value": "*"
      },
      "operatingSystem": {
        "type": "String",
        "value": "Windows Server 2019 with Containers"
      },
      "vmSize": {
        "type": "String",
        "value": "Standard_D4_v3"
      },
      "storageAccountType": {
        "type": "String",
        "value": "Standard_LRS"
      },
      "vmAdminUsername": {
        "type": "String",
        "value": "vmadmin"
      },
      "navAdminUsername": {
        "type": "String",
        "value": "admin"
      },
      "azureSqlAdminUsername": {
        "type": "String",
        "value": "sqladmin"
      },
      "adminPassword": {
        "type": "SecureString"
      },
      "navDockerImage": {
        "type": "String",
        "value": "mcr.microsoft.com/dynamicsnav:2017-de"
      },
      "registryUsername": {
        "type": "String",
        "value": ""
      },
      "registryPassword": {
        "type": "SecureString"
      },
      "licenseFileUri": {
        "type": "String",
        "value": ""
      },
      "sqlServerType": {
        "type": "String",
        "value": "SQLExpress"
      },
      "appBacpacUri": {
        "type": "String",
        "value": ""
      },
      "tenantBacpacUri": {
        "type": "String",
        "value": ""
      },
      "includeAppUris": {
        "type": "String",
        "value": ""
      },
      "enableSymbolLoading": {
        "type": "String",
        "value": "Yes"
      },
      "includeCSIDE": {
        "type": "String",
        "value": "Yes"
      },
      "clickOnce": {
        "type": "String",
        "value": "No"
      },
      "enableTaskScheduler": {
        "type": "String",
        "value": "Yes"
      },
      "multitenant": {
        "type": "String",
        "value": "No"
      },
      "office365UserName": {
        "type": "String",
        "value": ""
      },
      "office365Password": {
        "type": "SecureString"
      },
      "createAadUsers": {
        "type": "String",
        "value": "No"
      },
      "certificatePfxUrl": {
        "type": "String",
        "value": ""
      },
      "certificatePfxPassword": {
        "type": "SecureString"
      },
      "publicDnsName": {
        "type": "String",
        "value": ""
      },
      "finalSetupScriptUrl": {
        "type": "String",
        "value": ""
      },
      "bingMapsKey": {
        "type": "String",
        "value": ""
      },
      "requestToken": {
        "type": "String",
        "value": ""
      },
      "runWindowsUpdate": {
        "type": "String",
        "value": "No"
      },
      "contactEMailForLetsEncrypt": {
        "type": "String",
        "value": "***"
      },
      "autoShutdown": {
        "type": "String",
        "value": "Enabled"
      },
      "autoShutdownTime": {
        "type": "String",
        "value": "20:00"
      },
      "addTraefik": {
        "type": "String",
        "value": "No"
      }
```

Feedback from PowerShell:
```
Using image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
Country de
Version 10.0.29930.0
Locale de-DE
Running mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019 (this will take a few minutes)
NavContainerHelper is version 0.6.2.6
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.7
Docker Server Version is 18.09.7
Using image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
Publishing port 8080
Publishing port 443
Publishing port 7046
Publishing port 7047
Publishing port 7048
Publishing port 7049
PublicDnsName is ***.westeurope.cloudapp.azure.com
Removing navserver from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\navserver
Creating Container navserver
Version: 10.0.29930.0-de
Generic Tag: 0.0.9.9
Container OS Version: 10.0.17763.557 (ltsc2019)
Host OS Version: 10.0.17763.615 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\navserver\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupCertificate.ps1
- SetupConfiguration.ps1
- SetupWebClient.ps1
- SetupWindowsUsers.ps1
- updatehosts.ps1
Creating container navserver from image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
5574f9d4b11da0049ce61aec3f266b9d15df09f289653b6414a355156e7b4234
Waiting for container navserver to be ready
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Container output
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container navserver failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.6\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...avserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container navserver failed
```

Event Log Says:
```
Server instance: NAV
Tenant: 
<ii>The service MicrosoftDynamicsNavServer$NAV failed to start. This could be caused by a configuration error. Detailed error information: System.ArgumentException: It is likely that certificate 'CN=***.westeurope.cloudapp.azure.com' may not have a private key that is capable of key exchange or the process may not have access rights for the private key. Please see inner exception for detail. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.
```

Does anybody has a idea about that?

**Comment by freddydk** [comment]
Looks like there is a problem with the certificate. Try to use letsencrypt instead

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Chris Blank <notifications@github.com>
Sendt: Wednesday, July 17, 2019 4:13:23 PM
Til: microsoft/nav-arm-templates <nav-arm-templates@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/nav-arm-templates] Deployment of NAV 2017 failed (#116)


I tried to deploy NAV2017.

Parameters:

"parameters": {
      "vmName": {
        "type": "String",
        "value": "***"
      },
      "timezoneId": {
        "type": "String",
        "value": "GMT Standard Time"
      },
      "acceptEula": {
        "type": "String",
        "value": "Yes"
      },
      "remoteDesktopAccess": {
        "type": "String",
        "value": "*"
      },
      "operatingSystem": {
        "type": "String",
        "value": "Windows Server 2019 with Containers"
      },
      "vmSize": {
        "type": "String",
        "value": "Standard_D4_v3"
      },
      "storageAccountType": {
        "type": "String",
        "value": "Standard_LRS"
      },
      "vmAdminUsername": {
        "type": "String",
        "value": "vmadmin"
      },
      "navAdminUsername": {
        "type": "String",
        "value": "admin"
      },
      "azureSqlAdminUsername": {
        "type": "String",
        "value": "sqladmin"
      },
      "adminPassword": {
        "type": "SecureString"
      },
      "navDockerImage": {
        "type": "String",
        "value": "mcr.microsoft.com/dynamicsnav:2017-de"
      },
      "registryUsername": {
        "type": "String",
        "value": ""
      },
      "registryPassword": {
        "type": "SecureString"
      },
      "licenseFileUri": {
        "type": "String",
        "value": ""
      },
      "sqlServerType": {
        "type": "String",
        "value": "SQLExpress"
      },
      "appBacpacUri": {
        "type": "String",
        "value": ""
      },
      "tenantBacpacUri": {
        "type": "String",
        "value": ""
      },
      "includeAppUris": {
        "type": "String",
        "value": ""
      },
      "enableSymbolLoading": {
        "type": "String",
        "value": "Yes"
      },
      "includeCSIDE": {
        "type": "String",
        "value": "Yes"
      },
      "clickOnce": {
        "type": "String",
        "value": "No"
      },
      "enableTaskScheduler": {
        "type": "String",
        "value": "Yes"
      },
      "multitenant": {
        "type": "String",
        "value": "No"
      },
      "office365UserName": {
        "type": "String",
        "value": ""
      },
      "office365Password": {
        "type": "SecureString"
      },
      "createAadUsers": {
        "type": "String",
        "value": "No"
      },
      "certificatePfxUrl": {
        "type": "String",
        "value": ""
      },
      "certificatePfxPassword": {
        "type": "SecureString"
      },
      "publicDnsName": {
        "type": "String",
        "value": ""
      },
      "finalSetupScriptUrl": {
        "type": "String",
        "value": ""
      },
      "bingMapsKey": {
        "type": "String",
        "value": ""
      },
      "requestToken": {
        "type": "String",
        "value": ""
      },
      "runWindowsUpdate": {
        "type": "String",
        "value": "No"
      },
      "contactEMailForLetsEncrypt": {
        "type": "String",
        "value": "***"
      },
      "autoShutdown": {
        "type": "String",
        "value": "Enabled"
      },
      "autoShutdownTime": {
        "type": "String",
        "value": "20:00"
      },
      "addTraefik": {
        "type": "String",
        "value": "No"
      }


Feedback from PowerShell:

Using image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
Country de
Version 10.0.29930.0
Locale de-DE
Running mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019 (this will take a few minutes)
NavContainerHelper is version 0.6.2.6
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.7
Docker Server Version is 18.09.7
Using image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
Publishing port 8080
Publishing port 443
Publishing port 7046
Publishing port 7047
Publishing port 7048
Publishing port 7049
PublicDnsName is ***.westeurope.cloudapp.azure.com
Removing navserver from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\navserver
Creating Container navserver
Version: 10.0.29930.0-de
Generic Tag: 0.0.9.9
Container OS Version: 10.0.17763.557 (ltsc2019)
Host OS Version: 10.0.17763.615 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\navserver\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupCertificate.ps1
- SetupConfiguration.ps1
- SetupWebClient.ps1
- SetupWindowsUsers.ps1
- updatehosts.ps1
Creating container navserver from image mcr.microsoft.com/dynamicsnav:2017-de-ltsc2019
5574f9d4b11da0049ce61aec3f266b9d15df09f289653b6414a355156e7b4234
Waiting for container navserver to be ready
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Container output
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ***.westeurope.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container navserver failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.6\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...avserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container navserver failed


Event Log Says:

Server instance: NAV
Tenant:
<ii>The service MicrosoftDynamicsNavServer$NAV failed to start. This could be caused by a configuration error. Detailed error information: System.ArgumentException: It is likely that certificate 'CN=***.westeurope.cloudapp.azure.com' may not have a private key that is capable of key exchange or the process may not have access rights for the private key. Please see inner exception for detail. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.


Does anybody has a idea about that?

**Comment by ChrisBlankDe** [comment]
I tried it with letsencrypt.
Certificate is installed in container.

```
[NAVSERVER]: PS C:\Run> $CertificatePfxPassword = ConvertTo-SecureString -String "30f2578c-6a66-4d7f-922e-932297c*****" -AsPlainText -Force
$certificatePfxFile = "c:\ProgramData\navcontainerhelper\certificate.pfx"
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certificatePfxFile, $certificatePfxPassword)
$certificateThumbprint = $cert.Thumbprint
Write-Host "Certificate File Thumbprint $certificateThumbprint"
Certificate File Thumbprint 808C254E50678FFC3F88B041E86FE30A743F4BDF

[NAVSERVER]: PS C:\Run> Get-Item Cert:\LocalMachine\my\$certificateThumbprint


   PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\my

Thumbprint                                Subject                                                                                                                        
----------                                -------                                                                                                                        
808C254E50678FFC3F88B041E86FE30A743F4BDF  CN=***.westeurope.cloudapp.azure.com                                                                                 
```

Do i have to check the certificate permissions so nst could read it?
NST runs as SYSTEM in container by default. SYSTEM should always have permission, isn't it?

**Comment by freddydk** [comment]
It seems like NAV 2017 has a problem with letsencrypt
Just tried the same as you - if I change the image name in settings.ps1 to 2018-de and re-run setupnavcontainer - it works.
If I rename SetupCertificate in c:\myfolder to something else - then 2017-de gets a self-signed certificate - and that works too.
I don't know why 2017 doesn't support letsencrypt and it is not something that will have a high priority to investigate.
Solution is to delete the setupcertificate in c:\myfolder and use a self-signed certificate.
