### ISSUE TITLE
Install-Module powershellget not working

### ISSUE THREAD

**Issue by AIGARSJ** [microsoft/nav-arm-templates#157]
"Install-Module powershellget -RequiredVersion 2.2.1 -force" not working as expected
Actually it download and install version 2.2.4.1 so a command "Import-Module powershellget -RequiredVersion 2.2.1" fail with error:
"The specified module 'powershellget' with version '2.2.1' was not loaded because no valid module file was found in any module directory."

**Comment by freddydk** [comment]
Powershell gallery is down this morning

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: AIGARSJ <notifications@github.com>
Sendt: Friday, October 30, 2020 9:40:44 AM
Til: microsoft/nav-arm-templates <nav-arm-templates@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/nav-arm-templates] Install-Module powershellget not working (#157)


"Install-Module powershellget -RequiredVersion 2.2.1 -force" not working as expected
Actually it download and install version 2.2.4.1 so a command "Import-Module powershellget -RequiredVersion 2.2.1" fail with error:
"The specified module 'powershellget' with version '2.2.1' was not loaded because no valid module file was found in any module directory."

**Comment by AIGARSJ** [comment]
Powershell gallery is up and running. Issue resolved.
