### ISSUE TITLE
Failing releases with BcContainerHelper 3.0.2

### ISSUE THREAD

**Issue by ManuelvdM** [microsoft/nav-arm-templates#186]
Hi Freddy, 

Yesterday we had failing releases with the preview version of BcContainerHelper 3.0.2. Today we saw the 3.0.2 is in production. And we have the same issues now on our production releases.
BCArtifactsURL is the same as the successful release with version 3.0.1. 
The only difference is the BcContainerHelper version. Attached the log files of the 2 releases. 

We also tried to revered the BcContainerHelper version on the failed vm back to 3.0.1 and ran the SetupNavContainer.ps1 manually, but also the error about the credentials appears.

Can you have a look what is going wrong? This is blocking our daily releases.

Hope to hear from you soon,

Greetings Manuel van der Meijden
Cegeka

[Succesfull release with BcContainerHelper 3.0.1.txt](https://github.com/microsoft/nav-arm-templates/files/8031131/Succesfull.release.with.BcContainerHelper.3.0.1.txt)
[Failed release with BcContainerHelper 3.0.2-preview.txt](https://github.com/microsoft/nav-arm-templates/files/8031132/Failed.release.with.BcContainerHelper.3.0.2-preview.txt)

**Comment by freddydk** [comment]
Unfortunately, for reasons with artifacts for 18.9 and 17.14 – I had to push 3.0.2 to production right away (too many partners would run into problems in their scripts without this fix for a problem with the artifacts)

In 3.0.2, I modified the Create-AadAppsforBC to use a new API (MS Graph API) for App Creation instead of the old (Azure AD API).
I did not discover was, that you cannot have an AppIdUri with an ending /
I could strip that during creation – but then you would transfer the same to other places and it would fail there.

I think you can just remove the trailing slash in your code and things should work.

**Comment by ManuelvdM** [comment]
Closed this issue. Opened a new issue with new information and issue.
