### ISSUE TITLE
The server "NAV" was unable to process the request when using getbc 

### ISSUE THREAD

**Issue by ichladil** [Microsoft/nav-arm-templates#88]
Using getbc with BC13.4 I am encountering error:
The server "NAV" was unable to process the request

As described in here - https://github.com/Microsoft/navcontainerhelper/issues/381

I am not sure exactly which step is failing. But I was running full template (everything populated) with OnPrem W1 version and it was failing repeatedly.

**Comment by megel** [comment]
you have the logfile of the vm?

**Comment by MikkelLevin** [comment]
We experience the same problem, so let me a log below. You will see that the scripts continued when I started the VM today.
We think the problem happens when O365 is enabled in the ARM template. With no O365 the VM is created with no problems. It happens on all versions above 13.3.
Local deployment using NavContainerHelper does not fail.
We have tried with the following images:
microsoft/bcsandbox:dk
bcinsider.azurecr.io/bcsandbox:dk
mcr.microsoft.com/businesscentral/onprem:dk
mcr.microsoft.com/businesscentral/onprem:cu4-dk-ltsc2019
Thanks, Mikkel


9:38:42 AM at , : line 25
9:38:42 AM The server "NAV" was unable to process the request. The application will close.
9:33:50 AM Running microsoft/bcsandbox:dk-ltsc2019 (this will take a few minutes)
9:33:50 AM Locale da-DK
9:33:50 AM Version 13.4.28874.29517
9:33:50 AM Country DK
9:33:50 AM Using image microsoft/bcsandbox:dk-ltsc2019
9:33:47 AM Removing container navserver
9:32:36 AM Creating Aad Apps for Office 365 integration
9:32:33 AM Installing OpenXML 2.5
9:32:30 AM Installing SQL Native Client
9:32:19 AM Installing Visual C++ Redist
9:32:19 AM Digest: sha256:3471b3f4c174639fdbfb35a3ac79c3ffb9c57a1dc2aaf9595fce8b2dd9017949
9:32:19 AM dk-ltsc2019: Pulling from microsoft/bcsandbox
9:32:08 AM Pulling microsoft/bcsandbox:dk-ltsc2019 (this might take ~30 minutes)
9:32:07 AM Adding Landing Page to Startup Group
9:32:07 AM Add Import navcontainerhelper to PowerShell profile
9:32:07 AM Disabling Server Manager Open At Logon
9:32:07 AM Show hidden files and file types
9:32:07 AM Enabling Font Download in IE
9:32:07 AM Enabling File Download in IE
9:32:04 AM Enabling Docker API
9:32:02 AM Starting docker
9:31:56 AM SetupVm, User: vmadmin
9:31:42 AM Launch SetupVm
9:30:58 AM SetupStart, User: mdcbcdev0000012$
4:05:20 PM at , : line 25
4:05:20 PM The server "NAV" was unable to process the request. The application will close.
4:00:56 PM Running microsoft/bcsandbox:dk-ltsc2019 (this will take a few minutes)
4:00:56 PM Locale da-DK
4:00:56 PM Version 13.4.28874.29517
4:00:56 PM Country DK
4:00:56 PM Using image microsoft/bcsandbox:dk-ltsc2019
4:00:34 PM Creating Aad Apps for Office 365 integration
4:00:31 PM Installing OpenXML 2.5
4:00:28 PM Installing SQL Native Client
3:59:47 PM Installing Visual C++ Redist
3:59:47 PM Status: Downloaded newer image for microsoft/bcsandbox:dk-ltsc2019
3:59:47 PM Digest: sha256:3471b3f4c174639fdbfb35a3ac79c3ffb9c57a1dc2aaf9595fce8b2dd9017949
3:59:43 PM ee83a52e7229: Pull complete
3:59:42 PM d7e656e70c7e: Pull complete
3:57:52 PM b1081c9ca188: Pull complete
3:57:52 PM c9482a6a084a: Pull complete
3:57:51 PM f0af75073157: Pull complete
3:57:51 PM adb687442fd6: Pull complete
3:57:50 PM 7407dfc4aa57: Pull complete
3:57:50 PM edec12bfd659: Pull complete
3:57:45 PM 984264e74fa4: Pull complete
3:54:54 PM 8b3781a4ad11: Pull complete
3:54:53 PM f2b91fba3bcd: Pull complete
3:54:53 PM c3c82cada507: Pull complete
3:54:52 PM fe70da2d1412: Pull complete
3:54:52 PM b9525df11d17: Pull complete
3:54:51 PM d01668341ae2: Pull complete
3:54:51 PM 627c788891e6: Pull complete
3:54:50 PM 4c81e5c6a003: Pull complete
3:54:49 PM 107343bb9a3b: Pull complete
3:54:48 PM aa1393a8d5ed: Pull complete
3:54:47 PM 0cd0e614f20b: Pull complete
3:54:46 PM 8d6848879a86: Pull complete
3:54:45 PM 1c54899db345: Pull complete
3:54:44 PM 2b1f70e1f5a7: Pull complete
3:54:36 PM ab19846ae33a: Pull complete
3:54:35 PM 2536bf21eb79: Pull complete
3:52:13 PM 984264e74fa4: Download complete
3:52:13 PM 984264e74fa4: Verifying Checksum
3:52:10 PM d7e656e70c7e: Download complete
3:52:10 PM d7e656e70c7e: Verifying Checksum
3:52:07 PM ee83a52e7229: Download complete
3:52:07 PM ee83a52e7229: Verifying Checksum
3:52:06 PM b1081c9ca188: Download complete
3:52:06 PM b1081c9ca188: Verifying Checksum
3:52:06 PM c9482a6a084a: Download complete
3:52:06 PM c9482a6a084a: Verifying Checksum
3:52:06 PM f0af75073157: Download complete
3:52:06 PM f0af75073157: Verifying Checksum
3:52:06 PM adb687442fd6: Download complete
3:52:06 PM adb687442fd6: Verifying Checksum
3:52:06 PM 7407dfc4aa57: Download complete
3:52:06 PM 7407dfc4aa57: Verifying Checksum
3:52:06 PM 2536bf21eb79: Download complete
3:52:06 PM 2536bf21eb79: Verifying Checksum
3:52:05 PM edec12bfd659: Download complete
3:52:05 PM edec12bfd659: Verifying Checksum
3:52:05 PM 8b3781a4ad11: Download complete
3:52:05 PM 8b3781a4ad11: Verifying Checksum
3:52:05 PM f2b91fba3bcd: Download complete
3:52:05 PM f2b91fba3bcd: Verifying Checksum
3:52:04 PM c3c82cada507: Download complete
3:52:04 PM c3c82cada507: Verifying Checksum
3:52:04 PM fe70da2d1412: Download complete
3:52:04 PM fe70da2d1412: Verifying Checksum
3:52:04 PM b9525df11d17: Download complete
3:52:04 PM b9525df11d17: Verifying Checksum
3:52:04 PM 6f1b33e40b2b: Pull complete
3:52:04 PM d01668341ae2: Download complete
3:52:04 PM d01668341ae2: Verifying Checksum
3:52:04 PM 627c788891e6: Download complete
3:52:04 PM 627c788891e6: Verifying Checksum
3:52:03 PM 4c81e5c6a003: Download complete
3:52:03 PM 4c81e5c6a003: Verifying Checksum
3:52:03 PM 107343bb9a3b: Download complete
3:52:03 PM 107343bb9a3b: Verifying Checksum
3:52:03 PM aa1393a8d5ed: Download complete
3:52:03 PM aa1393a8d5ed: Verifying Checksum
3:52:03 PM c5e017fb50da: Pull complete
3:52:03 PM 0cd0e614f20b: Download complete
3:52:03 PM 0cd0e614f20b: Verifying Checksum
3:52:03 PM 8d6848879a86: Download complete
3:52:03 PM 8d6848879a86: Verifying Checksum
3:52:02 PM 34c2688c3d41: Pull complete
3:52:02 PM 2b1f70e1f5a7: Download complete
3:52:02 PM 2b1f70e1f5a7: Verifying Checksum
3:52:02 PM 1c54899db345: Download complete
3:52:02 PM 1c54899db345: Verifying Checksum
3:52:02 PM 90f827703008: Pull complete
3:52:02 PM ab19846ae33a: Download complete
3:52:02 PM ab19846ae33a: Verifying Checksum
3:52:02 PM 6f1b33e40b2b: Download complete
3:52:02 PM 6f1b33e40b2b: Verifying Checksum
3:52:01 PM 34c2688c3d41: Download complete
3:52:01 PM 34c2688c3d41: Verifying Checksum
3:52:01 PM 90f827703008: Download complete
3:52:01 PM 90f827703008: Verifying Checksum
3:52:01 PM c5e017fb50da: Download complete
3:52:01 PM c5e017fb50da: Verifying Checksum
3:52:01 PM ee83a52e7229: Waiting
3:52:01 PM d7e656e70c7e: Waiting
3:52:01 PM b1081c9ca188: Waiting
3:52:01 PM c9482a6a084a: Waiting
3:52:01 PM f0af75073157: Waiting
3:52:01 PM adb687442fd6: Waiting
3:52:01 PM 7407dfc4aa57: Waiting
3:52:01 PM edec12bfd659: Waiting
3:52:01 PM 984264e74fa4: Waiting
3:52:01 PM 8b3781a4ad11: Waiting
3:52:01 PM f2b91fba3bcd: Waiting
3:52:01 PM c3c82cada507: Waiting
3:52:01 PM fe70da2d1412: Waiting
3:52:01 PM b9525df11d17: Waiting
3:52:01 PM d01668341ae2: Waiting
3:52:01 PM 627c788891e6: Waiting
3:52:01 PM 4c81e5c6a003: Waiting
3:52:01 PM 107343bb9a3b: Waiting
3:52:01 PM aa1393a8d5ed: Waiting
3:52:01 PM 0cd0e614f20b: Waiting
3:52:01 PM 8d6848879a86: Waiting
3:52:01 PM 1c54899db345: Waiting
3:52:01 PM 2b1f70e1f5a7: Waiting
3:52:01 PM ab19846ae33a: Waiting
3:52:01 PM 2536bf21eb79: Waiting
3:52:01 PM 6f1b33e40b2b: Waiting
3:52:01 PM ee83a52e7229: Pulling fs layer
3:52:01 PM d7e656e70c7e: Pulling fs layer
3:52:01 PM b1081c9ca188: Pulling fs layer
3:52:01 PM c9482a6a084a: Pulling fs layer
3:52:01 PM f0af75073157: Pulling fs layer
3:52:01 PM adb687442fd6: Pulling fs layer
3:52:01 PM 7407dfc4aa57: Pulling fs layer
3:52:01 PM edec12bfd659: Pulling fs layer
3:52:01 PM 984264e74fa4: Pulling fs layer
3:52:01 PM 8b3781a4ad11: Pulling fs layer
3:52:01 PM f2b91fba3bcd: Pulling fs layer
3:52:01 PM c3c82cada507: Pulling fs layer
3:52:01 PM fe70da2d1412: Pulling fs layer
3:52:01 PM b9525df11d17: Pulling fs layer
3:52:01 PM d01668341ae2: Pulling fs layer
3:52:01 PM 627c788891e6: Pulling fs layer
3:52:01 PM 4c81e5c6a003: Pulling fs layer
3:52:01 PM 107343bb9a3b: Pulling fs layer
3:52:01 PM aa1393a8d5ed: Pulling fs layer
3:52:01 PM 0cd0e614f20b: Pulling fs layer
3:52:01 PM 8d6848879a86: Pulling fs layer
3:52:01 PM 1c54899db345: Pulling fs layer
3:52:01 PM 2b1f70e1f5a7: Pulling fs layer
3:52:01 PM ab19846ae33a: Pulling fs layer
3:52:01 PM 2536bf21eb79: Pulling fs layer
3:52:01 PM 6f1b33e40b2b: Pulling fs layer
3:52:01 PM c5e017fb50da: Pulling fs layer
3:52:01 PM 34c2688c3d41: Pulling fs layer
3:52:01 PM 90f827703008: Pulling fs layer
3:52:01 PM 9e2f2b17be72: Already exists
3:52:01 PM 65014b3c3121: Already exists
3:52:00 PM dk-ltsc2019: Pulling from microsoft/bcsandbox
3:51:55 PM Pulling microsoft/bcsandbox:dk-ltsc2019 (this might take ~30 minutes)
3:51:55 PM Adding Landing Page to Startup Group
3:51:55 PM Add Import navcontainerhelper to PowerShell profile
3:51:55 PM Disabling Server Manager Open At Logon
3:51:55 PM Show hidden files and file types
3:51:55 PM Enabling Font Download in IE
3:51:55 PM Enabling File Download in IE
3:51:54 PM Enabling Docker API
3:51:53 PM Starting docker
3:51:51 PM SetupVm, User: vmadmin
3:51:39 PM Launch SetupVm
3:51:26 PM Installing AzureAD PowerShell package
3:51:11 PM Installing AzureRM.Resources PowerShell package
3:50:56 PM Installing AzureRM.ApiManagement PowerShell package
3:50:52 PM SetupStart, User: mdcbcdev0000012$
3:48:34 PM Restarting computer and start Installation tasks
3:47:06 PM Using Lets Encrypt certificate
3:47:06 PM Using Nav Container Helper version 0.5.0.9
3:46:48 PM Installing Latest Nav Container Helper from PowerShell Gallery
3:46:48 PM Downloading C:\DEMO\Install-VS2017Community.ps1
3:46:47 PM Downloading c:\demo\SetupStart.ps1
3:46:47 PM Downloading c:\demo\SetupVm.ps1
3:46:47 PM Downloading c:\demo\SetupAAD.ps1
3:46:47 PM Downloading c:\demo\SetupNavContainer.ps1
3:46:47 PM Downloading c:\demo\SetupDesktop.ps1
3:46:47 PM Downloading c:\myfolder\SetupWebClient.ps1
3:46:46 PM Turning off IE Enhanced Security Configuration
3:46:46 PM Creating Connect.rdp
3:46:46 PM Downloading C:\inetpub\wwwroot\web.config
3:46:46 PM Downloading C:\inetpub\wwwroot\Microsoft.png
3:46:46 PM Downloading C:\inetpub\wwwroot\line.png
3:46:46 PM Downloading C:\inetpub\wwwroot\status.aspx
3:46:45 PM Downloading C:\inetpub\wwwroot\default.aspx
3:44:16 PM Installing Internet Information Server (this might take a few minutes)
3:44:00 PM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/getnav.json
3:44:00 PM Initialize, user: mdcbcdev0000012$
3:44:00 PM Running Windows Server 2019 Datacenter
3:44:00 PM Starting initialization

**Comment by freddydk** [comment]
Invoke-NavCodeunit does not work in 13.4.
This means that AAD authentication is currently broken and test users was also.

Right now only option is to use cu3 for onprem (or update22 for sandbox)

The fix is to change .fob files to apps, publish those and use apis to invoke them - will be fixed as soon as possible - but no promises given

**Comment by MikkelLevin** [comment]
Ok. We understand.
Thanks.

**Comment by freddydk** [comment]
This should work now.
